# File này cần được đặt trong Git repository mà Config Server đang theo dõi
# Thường đặt tại: config-repo/phk-problemsknowledgehub.yml

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/keycloak-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/keycloak-realm

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,beans,env,metrics,prometheus
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true

logging:
  level:
    com.phk: INFO
    org.springframework.cloud: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application specific configurations
app:
  name: PHK Problems Knowledge Hub
  version: 1.0.0
  description: Service for managing problems and knowledge base
